### ISSUE TITLE
可以用右上角的“copy”按钮代替双击实现复制功能吗

### ISSUE THREAD

**Issue by guyon168** [Nriver/copy-code-block-widget#1]
类似东东大佬的博客主题中实现的效果，可以一键copy代码块。是否可以把双击动作替换成复制按钮
https://www.ankia.top/3LdIi2f30Pan
![Uploading 复制按钮.png…]()

**Comment by guyon168** [comment]
@
![Uploading 复制按钮.png…]()

**Comment by Nriver** [comment]
不行，编辑器里无法实现。
